
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module IT_LAB_12(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// ADC //////////
	output		          		ADC_CONVST,
	output		          		ADC_DIN,
	input 		          		ADC_DOUT,
	output		          		ADC_SCLK
);


//=======================================================
//  REG/WIRE declarations
//=======================================================
// For Platform Designer block
logic PLL_locked, AD_clk, reset_n;

// For clock Gate
logic ADC_clk_en = 0;

// logic gated_AD_clk;
// assign ADC_SCLK = gated_AD_clk;

// For Binary to BCD function
logic [11:0] binary_in;
logic [15:0] bcd_out;

assign reset_n = KEY[0];

//=======================================================
//  Structural coding
//=======================================================
PD_L12 u0 (
	.clk_clk             (CLOCK_50),             //           clk.clk
	.reset_reset_n       (reset_n),       //         reset.reset_n
	.pll_0_locked_export (PLL_locked), //  pll_0_locked.export
	.pll_0_outclk0_clk   (AD_clk)    // pll_0_outclk0.clk
);

clk_gate u1 (
	.clk_in		(AD_clk),
	.enable		(ADC_clk_en), 
	.reset		( (~reset_n) & (~PLL_locked) ), 
	.clk_out	(ADC_SCLK) // OPTIONALLY: gated_AD_clk
);

ADC_controller u2 (
	.ADC_clk(AD_clk),
	.SDO	(ADC_DOUT),
	.SDI 	(ADC_DIN),
	.CONVST (ADC_CONVST),
	.binval	(binary_in),
	.switch	(SW[2:0]),
	.ADC_clk_en
);

bin2bcd u3 (
	.binary_in,
	.bcd_out
);

segment7 u4 (
	.bcd	(bcd_out[3:0]), 
	.seg	(HEX0)
);

segment7 u5 (
	.bcd	(bcd_out[7:4]), 
	.seg	(HEX1)
);

segment7 u6 (
	.bcd	(bcd_out[11:8]), 
	.seg	(HEX2)
);

segment7 u7 (
	.bcd	(bcd_out[15:12]), 
	.seg	(HEX3)
);

endmodule
