
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module IT_LAB_8(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

PLATFORM_DES_LAB_8 u0 (
    .clk_clk                  (CLOCK_50),                  				//                clk.clk
    .reset_reset_n            (KEY[0]),            						//              reset.reset_n
    .clk_143_ps_clk           (DRAM_CLK),           					//         clk_143_ps.clk
    .pll_locked_export        (),       								//         pll_locked.export
    .sdram_if_addr            (DRAM_ADDR),            					//           sdram_if.addr
    .sdram_if_ba              (DRAM_BA),              					//                   .ba
    .sdram_if_cas_n           (DRAM_CAS_N),                   			//                   .cas_n
    .sdram_if_cke             (DRAM_CKE),             					//                   .cke
    .sdram_if_cs_n            (DRAM_CS_N),            					//                   .cs_n
    .sdram_if_dq              (DRAM_DQ),              					//                   .dq
    .sdram_if_dqm             ({DRAM_UDQM, DRAM_LDQM}),                 //                   .dqm
    .sdram_if_ras_n           (DRAM_RAS_N),           					//                   .ras_n
    .sdram_if_we_n            (DRAM_WE_N),            					//                   .we_n
    .pio_export               (LEDR),               					//                pio.export
    .master_0_clk_reset_reset ()  										// master_0_clk_reset.reset
);


endmodule
