
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module IT_HW_9(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR
);


	logic pio_1_bit_export, reset_reset_n;
	assign LEDR[9] = pio_1_bit_export;
	assign LEDR[8] = 'b0;
	assign reset_reset_n = 'b1;

	logic [7:0] pio_8_bit_export;
	assign LEDR[7:0] = pio_8_bit_export;
	
	logic [9:0] pio_10_bit_export;
	assign pio_10_bit_export = SW[9:0];


	HW_8_PD u1(CLOCK_50, pio_10_bit_export, pio_1_bit_export, pio_8_bit_export, reset_reset_n);


endmodule
